- name: Revert commit (auto-resolve)
        run: |
          git revert a29ce561807e3fc53fac7e09d548c2d2f3e25854 || true
          git rm app/src/main/java/com/winlator/cmod/ExternalControllerBindingsActivity.java
          git add .
          git revert --continue
